apiVersion: kuma.io/v1alpha1
kind: MeshGatewayInstance
metadata:
  name: edge-gateway
  namespace: otel-demo
spec:
  replicas: 1
  serviceType: LoadBalancer
  tags:
    kuma.io/service: oteldemo_gateway
---