apiVersion: kuma.io/v1alpha1
kind: MeshTimeout
metadata:
  name: timeout-productcatalog
  namespace: kuma-system
  labels:
    kuma.io/mesh: default
spec:
  targetRef:
    kind: MeshService
    name: opentelemetry-demo-frontend_otel-demo_svc_8080
  from:
  - targetRef:
      kind: Mesh
    default:
      idleTimeout: 20s
      connectionTimeout: 2s
      http:
        requestTimeout: 5s
  to:
  - targetRef:
      kind: MeshService
      name: opentelemetry-demo-productcatalogservice_otel-demo_svc_8080
    default:
      idleTimeout: 20s
      connectionTimeout: 1s
      http:
        requestTimeout: 100ms
  - targetRef:
      kind: MeshService
      name: opentelemetry-demo-cartservice_otel-demo_svc_8080
    default:
      idleTimeout: 20s
      connectionTimeout: 1s
      http:
        requestTimeout: 60ms
---
apiVersion: kuma.io/v1alpha1
kind: MeshTimeout
metadata:
  name: timeout-gateway
  namespace: kuma-system
  labels:
    kuma.io/mesh: default
spec:
  targetRef:
    kind: MeshService
    name: oteldemo-gateway
  to:
  - targetRef:
      kind: MeshService
      name: opentelemetry-demo-frontend_otel-demo_svc_8080
    default:
      idleTimeout: 20s
      connectionTimeout: 2s
      http:
        requestTimeout: 1s
